import React from 'react';

const Log = window.Log;
const { REACT_APP_SERVER } = process.env;
Log.info({ REACT_APP_SERVER });
const configUpdate = (e) => {
    const { target } = e.nativeEvent;
    const { name, value } = target;
    Log.info({ name, value });
};

export const ConfigOptions = {
    form: {
        name: 'react-express-container-' + Date.now(),
        port: 3000,
        socket: false,
        code: 'false',
        readonly: 'false',
        dateModified: Date.now(),
        services: {
            mysql: {
                active: 'false',
                config: {
                    name: 'server-mysql',
                    host: 'localhost',
                    port: 3306,
                    pass: '',
                    database: ''
                },
                source: 'false',
                backup: 'false'
            
            },
            redis: {
                active: 'false',
                config: {
                    name: 'server-redis',
                    host: 'localhost',
                    port: 6379,
                    pass: '',
                    database: ''
                },
                source: 'false',
                backup: 'false'
            },
            mongo: {
                active: 'false',
                config: {
                    name: 'server-mongo',
                    host: 'localhost',
                    port: 27017,
                    pass: '',
                    database: ''
                },
                source: 'false',
                backup: 'false'
            },
        }
    },
    configUpdate
};

export const ConfigContext = React.createContext({
    ...ConfigOptions,
    configUpdate
});

/* DO NOT EDIT THIS FILE UNLESS YOU WANT TO CUSTOMIZE CONFIG.
*   This file is for core app configuration and not custom app.
*   AppContext.js should be used to add configuration for custom app.
*/
